version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/java:17
    volumes:
      - ../..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=serverdb
      - MYSQL_USER=serverdbadmin
      - MYSQL_PASSWORD=12345

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: serverdb
      MYSQL_USER: serverdbadmin
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: