version: '3.8'
services:
  app:
    image: mcr.microsoft.com/devcontainers/java:17
    volumes:
      - ../..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace/turbo-potato
    command: sleep infinity
    depends_on:
      mysql:
        condition: service_healthy  # Wait for MySQL to be ready
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=serverdb
      - MYSQL_USER=serverdbadmin
      - MYSQL_PASSWORD=12345
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: serverdb
      MYSQL_USER: serverdbadmin
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_HOST: '%'  # Allow root connections from any host
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d  # Optional: for init scripts
    networks:
      - app-network
    # Add health check to ensure MySQL is ready
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 20s
      retries: 10
      interval: 5s
      start_period: 30s
    # MySQL performance tuning for development
    command: >
      --default-authentication-plugin=mysql_native_password 
      --innodb-buffer-pool-size=128M
      --innodb-log-file-size=32M
      --max-connections=200
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge
